name: Download Neubaukompass Data

on:
  push:
    paths:
    - 'property_data/property_data/*'
  schedule:
    - cron:  '0 8/24 * * *'
  workflow_dispatch:
    inputs:
      whotriggered:
        description: 'Manual Trigger'
        default: 'Why'
        required: false


jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Get current directory and files
        run: |
          pwd
          ls
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install Python Requirements
        run: |
          python --version
          pip install -r requirements.txt
      - name: Download Records
        run: |
          cd property_data
          scrapy crawl neubaukompass -O data/neubaukompass-${{ steps.date.outputs.date }}.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git status
          git add .
          git commit -m "Update immowelt Dataset" || echo "Nothing to update"
          git config pull.rebase true
          git pull
          git status
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: hllmfamily/property-search
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}